export const stocks = [
    { id: 1, name: " Stock Name", },
    { id: 2, name: " Stock Name", },
    { id: 3, name: " Stock Name", },
    { id: 4, name: " Stock Name", },
    { id: 5, name: " Stock Name", },
    { id: 6, name: " Stock Name", },
    { id: 7, name: " Stock Name", },
    { id: 8, name: " Stock Name", },
    { id: 9, name: " Stock Name", },
    { id: 10, name: " Stock Name", },
    { id: 11, name: " Stock Name", },
    { id: 12, name: " Stock Name", },
    { id: 13, name: " Stock Name", },
    { id: 14, name: " Stock Name", },
    { id: 15, name: " Stock Name", },
    { id: 16, name: " Stock Name", },
    { id: 17, name: " Stock Name", },
    { id: 18, name: " Stock Name", },
];